### ISSUE TITLE
Missing 'package' key attribute on element package at [ir.tapsell.sdk:tapsell-sdk-android:4.7.1] AndroidManifest.xml:24:9-55

### ISSUE THREAD

**Issue by hsnMoghadasi** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#5] opened 2021-07-23 14:53 UTC
i just run 
`npm install react-native-tapsell-plus --save`
and then 
`npx react-native run-android`
and i got this error 

![image](https://user-images.githubusercontent.com/41155266/126800165-96393cb3-bd0f-48ab-a580-aed5ed7f0992.png)

    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-firebase/app": "^11.1.2",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "axios": "^0.21.1",
    "moment-jalaali": "^0.9.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-fast-image": "^8.3.4",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^11.7.0",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^2.0.0",
    "react-native-screens": "^2.8.0",
    "react-native-tapsell-plus": "^2.1.3",
    "react-native-vector-icons": "^8.1.0",
    "react-test-renderer": "16.9.0"

what could i do, pls help me

**Comment by hsnMoghadasi** [comment] 2021-08-04 08:19
can someone help me ?!

**Comment by hsnMoghadasi** [comment] 2021-08-04 08:22
> Task :app:processDebugManifest FAILED
[ir.tapsell.sdk:tapsell-sdk-android:4.7.2] C:\Users\Lenovo\.gradle\caches\transforms-2\files-2.1\a70ac391a7f0f3cb0ef35f1b2a5059f0\AndroidManifest.xml:24:9-55 Error:
	Missing 'package' key attribute on element package at [ir.tapsell.sdk:tapsell-sdk-android:4.7.2] AndroidManifest.xml:24:9-55
[ir.tapsell.sdk:tapsell-sdk-android:4.7.2] C:\Users\Lenovo\.gradle\caches\transforms-2\files-2.1\a70ac391a7f0f3cb0ef35f1b2a5059f0\AndroidManifest.xml Error:
	Validation failed, exiting

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by mahdi-malv** [comment] 2021-08-12 20:34
Sorry for the late response.

The error seems to be related to a wrecked package download by gradle (Couldn't reproduce it though). 
The error could be resolved by removing `C:\Users\Lenovo.gradle\caches\transforms-2\files-2.1\a70ac391a7f0f3cb0ef35f1b2a5059f0\` folder (also `C:\Users\Lenovo.gradle\caches\modules-2\files-2.1\ir.tapsell.sdk`)

If still wasn't fixed, please notify me in this issue.

**Comment by mahdi-malv** [comment] 2021-08-18 18:08
Some users have reported that this issue happens for them as well. The reason seems to be the version of Android Gradle plugin which needs to be `3.6.0` or higher. For instance sample (which never experienced this issue) uses `4.1.1` of AGP

Ref: Sample [gradle file](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativeSample/blob/864fa2bf05f9b6801940d570ef9388602edef1b1/android/build.gradle#L15)

**Comment by mahdi-malv** [comment] 2021-08-21 05:49
@hsnMoghadasi Any luck?

**Closed** 2021-09-01 08:51 UTC
Labels: impl_error
