### ISSUE TITLE
Get error when running ios version

### ISSUE THREAD

**Issue by AlirezaHadjar** [tapsellorg/TapsellPlusSDK-ReactNativePlugin#7] opened 2021-08-12 15:29 UTC
When I use `TapsellPlus.initialize(AD_APP_KEY)` I got this error
<img width="456" alt="Screen Shot 1400-05-21 at 19 57 53" src="https://user-images.githubusercontent.com/57192409/129224539-e5d954a8-9f97-422e-ab7e-cde0c151d5d2.png">

**Comment by mahdi-malv** [comment] 2021-08-12 20:36
Thank for reporting this error
The error is related to [this part](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativePlugin/blob/920cf71434f6e08e3b0cb6de4bd3e768c56cf0b3/src/constants.js#L1) of the code.

The problem is this module does not exist in iOS, since the plugin is implemented only in Android native side.

Will be fixed in the next version.
**Temp solution** would be importing tapsell under a certain condition and that is checking if the Platform is Android. Otherwise `TapsellPlus#index.js` should not be executed

**Comment by MortezaNedaei** [comment] 2023-03-05 17:17
Feel free to reopen if still happens

**Closed by MortezaNedaei** 2023-03-05 17:17 UTC
Labels: bug
